---
- name: execute script
  hosts: srv1
  tasks:
    
    - name: Copy the file from srv1 to srv2 using Method Pull
      tags: sync-pull
      ansible.posix.synchronize:
        src: "{{ prod_directory + '/*' }}"
        dest: "{{ backup_directory}}"
        mode: pull
      delegate_to: srv2
      register: syncfile

    - name: find all files that are older than 10 min
      find:
        paths: "{{prod_directory}}"
        age: "{{old_than}}"
        recurse: yes
      register: filesOlderThan10
      when: syncfile.changed== True

    - name: remove files older than 10
      file:
        path: "{{ item.path }}" 
        state: absent
      with_items: "{{ filesOlderThan10.files }}"
      when: syncfile.changed== True

      


    
